//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinBlogEducation.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinBlogEducation.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string action_settings {
            get {
                return ResourceManager.GetString("action_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Posts.
        /// </summary>
        public static string AllPostsTitle {
            get {
                return ResourceManager.GetString("AllPostsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XamarinBlogEducation.Android.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes were saved.
        /// </summary>
        public static string BreakeEditPost {
            get {
                return ResourceManager.GetString("BreakeEditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new post.
        /// </summary>
        public static string CreatePostTitle {
            get {
                return ResourceManager.GetString("CreatePostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In details.
        /// </summary>
        public static string DetailedPostTitle {
            get {
                return ResourceManager.GetString("DetailedPostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords doesn`t the same!.
        /// </summary>
        public static string DifferentPasswords {
            get {
                return ResourceManager.GetString("DifferentPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your post.
        /// </summary>
        public static string EditPostTitle {
            get {
                return ResourceManager.GetString("EditPostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, write something.
        /// </summary>
        public static string EmptyComment {
            get {
                return ResourceManager.GetString("EmptyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill all the gaps.
        /// </summary>
        public static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong data. No changes was applied.
        /// </summary>
        public static string ErrorChangePassword {
            get {
                return ResourceManager.GetString("ErrorChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save changes.
        /// </summary>
        public static string ErrorChangeProfile {
            get {
                return ResourceManager.GetString("ErrorChangeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t comment.
        /// </summary>
        public static string ErrorComment {
            get {
                return ResourceManager.GetString("ErrorComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete this post.
        /// </summary>
        public static string ErrorDeletePost {
            get {
                return ResourceManager.GetString("ErrorDeletePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t edit this post. Check your input data.
        /// </summary>
        public static string ErrorEditPost {
            get {
                return ResourceManager.GetString("ErrorEditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Can&apos;t add new one.
        /// </summary>
        public static string ErrorPost {
            get {
                return ResourceManager.GetString("ErrorPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your post was deleted.
        /// </summary>
        public static string PostDeleted {
            get {
                return ResourceManager.GetString("PostDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All changes were saved.
        /// </summary>
        public static string ProfileChangesMessage {
            get {
                return ResourceManager.GetString("ProfileChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category was successfuly added.
        /// </summary>
        public static string SuccessAddCategory {
            get {
                return ResourceManager.GetString("SuccessAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was changed.
        /// </summary>
        public static string SuccessChangePassword {
            get {
                return ResourceManager.GetString("SuccessChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comment was successfuly added.
        /// </summary>
        public static string SuccessComment {
            get {
                return ResourceManager.GetString("SuccessComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your post was deleted.
        /// </summary>
        public static string SuccessDeletePost {
            get {
                return ResourceManager.GetString("SuccessDeletePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All changes were saved.
        /// </summary>
        public static string SuccessEditPost {
            get {
                return ResourceManager.GetString("SuccessEditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully logged in.
        /// </summary>
        public static string SuccessLogin {
            get {
                return ResourceManager.GetString("SuccessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your post was successfuly added.
        /// </summary>
        public static string SuccessPost {
            get {
                return ResourceManager.GetString("SuccessPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My posts.
        /// </summary>
        public static string UserPostsTitle {
            get {
                return ResourceManager.GetString("UserPostsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string UserProfileTitle {
            get {
                return ResourceManager.GetString("UserProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong format of email.
        /// </summary>
        public static string WrongEmailFormat {
            get {
                return ResourceManager.GetString("WrongEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong mail or password.
        /// </summary>
        public static string WrongLogin {
            get {
                return ResourceManager.GetString("WrongLogin", resourceCulture);
            }
        }
    }
}
